### PR TITLE
Big wave of CM's automation system for Qualcomm devices [DO NOT MERGE]

### PR DESCRIPTION
**Pull request by GalaticStryder**
Includes pathmapping support, ability to automate qcom compilation flags per board, bash/zsh fixes, build.prop overriding and some more utilities to be used on other Qualcomm devices such as custom mkbootimg scripts. Merge only on a big wave since it can potentially break the builds. Repos that need to be pushed to AOSPA will be listed on manifest commit.

### CODE REVIEW

**Comment by xboxfanj** [comment]
Much of this is not necessary. If you include device/qcom/common/BoardConfigCommon.mk, you will have the necessary flags such as qcom_bsp. Path map is also unnecessary as we use room service to pick the correct hal for each device and only support caf devices so no need to provide for Nexus. We already have qcom_utils.mk in build/core/tasks so any of those commits aren't needed.

This pull request is now closed, but feel free to create a smaller one with only the relevant changes.

**Comment by GalaticStryder** [comment]
@xboxfanj I got it. Actually compiled without all this just fine for the LG G2, only needed change is for bumping my recovery/boot images: https://github.com/AOSPA/android_build/pull/8/commits/d26c1cc31c2bca6d01c0f8a2bb34dcb573aacf19

**Comment by xboxfanj** [comment]
Thank you. I'll add that.

**Comment by xboxfanj** [comment]
Merged, thank you @GalaticStryder

**Pull request closed without merging**
